Movies list and details views
not-a-unicorn/movie-app-ui-web pull request #1
Opened 2018-10-20 02:23 UTC by gokuvinoth

Please review and comment.

2018-10-20 22:56 UTC, siraskalot requested changes
Generally looks OK, some changes suggested

2018-10-20 22:56 UTC, siraskalot commented on index.html
> +    <meta charset="8-utf">
utf-8 NOT 8-utf

2018-10-20 22:56 UTC, siraskalot commented on index.html
> +    <meta name='viewport' content='width=device-width, initial-scale=1.0' />
No need to have self-closing tag in HTML5

2018-10-20 22:56 UTC, siraskalot commented on styles/main.css
> +}
Add new line after this line

2018-10-20 22:56 UTC, siraskalot commented on styles/main.css
> +  color: whitesmoke;
Better to be consistent, either use hex colour codes `#000000`, colour names `black` or RGB syntax `rgb(0, 0, 0,)` not a mix

2018-10-20 22:56 UTC, siraskalot commented on styles/main.css
> +  font-family: "Hammersmith One", sans-serif;
Please remove this font-family declaration, you should only have 1 body font, and 1 other font for titles styles (maybe). Per element styles will make the app slow, and `Hammersmith One` is not a common font, so it won't work everywhere

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +renderHtml = responseData => {
- [x] Assign to variable `const`?
- [x] `movie` might be better name than `responseData`?
- [x] `movieItemTemplate` might be better than `renderHtml`?

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +            responseData.rating
What if rating is `null`?

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +const chkNull = (val, defaultVal) => {
Unused function can be deleted?

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +  return `
Better to split the template into a variable like `ratingTemplate` and then `return ratingTemplate` 💡

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +  ${'<i class="fas fa-star movie-star-rating"  aria-hidden=" true"></i>'.repeat(
Why the space before `true`?

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +  ${'<i class="fas fa-star-half-alt movie-star-rating" aria-hidden=" true"></i>'.repeat(
See previous comment

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +  ${'<i class="far fa-star movie-star-rating"  aria-hidden=" true"></i>'.repeat(
See previous comment

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +// mapping response to respective HTML elements
Weak comment, what response to what HTML elements?

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +const changeTitle = titleValue => {
`titleValue` could just be named `title`?

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +let resultElement = document.querySelector("#movies");
`resultElement` is ambiguous, `moviesList` might be better?

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +const displayListView = apiData => {
`initialiseMoviesList` or `initMoviesList` might be better name?

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +  let thumbnails = document.querySelectorAll("#movielist > li");
- `#movielist > .movie` would be a better selector, what if your `li` changes to `div` later?
- `movie` would be better name than `thumbnails`

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +const NavDetailview = id => {
Better name would be `renderMovieDetails`

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +      // Set clicked image as display image.
Un-needed comment, it's easy to understand what's happening based on code

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +    sessionDateTimes.forEach(sessionDateTime => {
Why is this repeated? See code-block above.

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +  function createSessionhtml(sessionDateTimes) {
`renderSessionDetails` would be better name?

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +    let dateTimeHtmlElement = "";
`sessionTemplate` might be better name?

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +  let backBtn = document.querySelector("#detailsBackBtn");
Let's not randomly abbreviate names, `backButton` might be better name?

2018-10-20 22:56 UTC, siraskalot commented on scripts/main.js
> +
Consider wrapping this in a function and calling that function.

2018-10-21 09:18 UTC, gokuvinoth commented on scripts/main.js
> +const chkNull = (val, defaultVal) => {
deleted.

2018-10-21 09:20 UTC, gokuvinoth commented on scripts/main.js
> +            responseData.rating
If rating is `null` then there will 5 empty stars denoting the its unrated.

2018-10-25 11:28 UTC, siraskalot reviewed
Nice work

2018-10-25 11:28 UTC, siraskalot approved these changes

2018-10-25 11:28 UTC, merged